# file: postgresql/tasks/extensions/networker.yml
- file:
    path: "/var/lib/postgresql/9.4/main/backup/archive"
    state: "directory"
    mode: "700"
    owner: "postgres"
    group: "postgres"

- name: PostgreSQL | Extensions | Adding networker pre and post backup commands
  copy:
    src: "{{item}}"
    dest: "/usr/bin/"
    owner: "root"
    mode: "755"
  with_fileglob:
    - "{{ role_path }}/files/networker/*"
