# file: postgresql/tasks/extensions/networker.yml

- name: Networker agent | create backup repository
  file:
    path: "{{ postgresql_backup_dir }}"
    state: "directory"
    owner: "postgres"
    group: "postgres"


- name: PostgreSQL | Extensions | Adding networker pre and pg_dumpall scripts
  template:
    src: "{{ item }}"
    dest: "/usr/sbin/"
  with_fileglob:
    - "{{ role_path }}/files/networker/*"
