#!/bin/sh
backupdir={{ postgresql_backup_dir }}

test -d $backupdir && rm -rf $backupdir/* 2>&1

# pour memoire backup pit WAL
#su - postgres -c "/usr/bin/pg_basebackup -p 5432 -U replicator -w -D /tmp/pg_backup/basebackup -X stream -F plain --verbose -h 127.0.0.1 2>&1 | tee -a $logfile "

# Make backup only if slave or master without slave
is_slave= `su - postgres -c "psql -tc 'SELECT pg_is_in_recovery();'"`
have_slave= `su - postgres -tc "psql SELECT (*) from pg_stat_replication;"`
if [[ is_slave -eq "f" ]]
then
	if [[ have_slave -eq "1" ]]
	then
		echo "Do not backup"
		exit -1
	fi
fi

# backup des users
su - postgres -c "/usr/bin/pg_dumpall -v --roles-only -f $backupdir/useraccts.sql"

# backup each database
DBLIST=`su - postgres -c "psql -tc 'select datname from pg_database ;'"`
for i in $DBLIST
do
        echo "pg_dump $i";
        su - postgres -c "pg_dump --format=custom $i --file=$backupdir/$i.sql"
done

# pour memoire fourtout
#su - postgres -c "/usr/bin/pg_dumpall -p 5432 -U postgres -w > $backupdir/pg_dumpall.dmp 2>&1

