#!/bin/sh

# pour memoire avec du WAL :
#/usr/bin/pg_archivecleanup -d /tmp/pg_backup/archive `cd /tmp/pg_backup/archive; ls -1rt *.backup| tail -1`  2>&1 | tee -a /tmp/nsrpost.log

echo ' Removing base_backup'
rm -f {{postgresql_archive_command}}/pg_dumpall.dmp 2>&1 | tee -a /tmp/nsrpost.log
