#!/bin/sh
su - postgres -c 'touch /tmp/nsrpre.log'
su - postgres -c 'test -d "/tmp/pg_backup" && mkdir /tmp/pg_backup'
date >> /tmp/nsrpre.log
export >> /tmp/nsrpre.log

id >> /tmp/nsrpre.log

su - postgres -c "/usr/bin/pg_basebackup -p 5432 -U replicator -w -D /tmp/pg_backup/basebackup -X stream -F plain --verbose -h 127.0.0.1 2>&1 | tee -a /tmp/nsrpre.log "
